apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
commonLabels:
  environment: dev
patches:
  - path: podinfo-values-dupa.yaml
    target:
      kind: HelmRelease
