name: Promote Dev to Int Overlay

on:
  push:
    branches:
      - master
    paths:
      - kubernetes/app/dev/**
permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for branch creation

      # Step 2: Set up yq for YAML processing
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      # Step 3: Synchronize Overlays (Exclude Fields)
      - name: Synchronize Dev to Int
        run: |
          # Sync changes from dev to int
          rsync -av --delete kubernetes/app/dev/ kubernetes/app/int/ --exclude 'fields-to-preserve.yml'
          
          cat kubernetes/app/int/kustomization.yml

          # Reapply preserved fields using yq
          yq eval-all 'select(fileIndex == 1) * select(fileIndex == 0)' kubernetes/app/int/fields-to-preserve.yml kubernetes/app/int/kustomization.yml > kubernetes/app/int/kustomization.yml.updated
          mv kubernetes/app/int/kustomization.yml.updated kubernetes/app/int/kustomization.yml
          
          echo ""
          echo ""
          echo ""
          echo "updated"
          cat kubernetes/app/int/kustomization.yml

      - name: Delete Branch If Exists
        run: |
          if git ls-remote --heads origin promotion/dev-to-int; then
            git push origin --delete promotion/dev-to-int
          fi

      # Step 4: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b promotion/dev-to-int
          git add kubernetes/app/int/**
          
          echo ""
          echo ""
          cat kubernetes/app/int/kustomization.yml
          
          git status
          git log --oneline
          ls -la kubernetes/app/int/   
                  
          git commit -m "Promote changes from dev to int overlay"
          git push origin promotion/dev-to-int
          git fetch --all

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: promotion/dev-to-int

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          gh pr create \
            --base master \
            --head promotion/dev-to-int \
            --title "[Promotion] Dev to Int Overlay" \
            --body "This PR promotes changes from the dev overlay to the int overlay."
